### ISSUE TITLE
Schematic

### ISSUE THREAD

**Issue by x893** [uXeBoy/VGA1306#2]
Hi,
awesome project !
Possible add schematic in pdf format ?

Thanks in advance
Mitek

**Comment by uXeBoy** [comment]
Howdy - I've just uploaded the Eagle files and BOM to the GitHub repository as a ZIP file... SO GO NUTS!

If you do end up making a run of boards then count me in for one or two! 😅

Fair warning - the schematic is kind of ugly, I was only really using it for connecting the necessary signals together and didn't take the time to make it pretty.

This was for the 'prototype' batch of 10 autorouted boards - Matt at kitsch-bent then took these files and worked on a nicer manually routed PCB for the boards that were sold on his shop.

The part numbers in the BOM that start with '3' are from Seeed's "open parts library" (parts that they always carry in stock):

https://www.seeedstudio.com/opl.html
